---
title: "Cannabis Visualizations"
author: "Lisa Marie Pritchett"
date: "January 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Clear environment
rm(list=ls())
library(dplyr)
library(stringr) 
library(tidyr)
library(ggplot2)
library(XLConnect) # reads excel
library(leaflet) # creates maps
library(prettydoc) # html formatting
source("http://peterhaschke.com/Code/multiplot.R")


setwd('../data')
source('get_data.R')
```





```{r}
# options for users
my_kind = c('Combined','medical','recreational')[3]
my_y = c('USD','perCapita','perStore')[1]
estimate_option = T

# Select on the y chosen
#y_total=select(my_summary,my_y)





# Select on the y chosen
#y_total=select(my_summary,my_y)


# Create summary for each County and Type, summing sales across years  
cannabis.summary <- cannabis.sales %>% 
            group_by(County,type,is.medical,is.Combined,is.Estimate,kind) %>% 
            summarise(n.stores=mean(n.stores,na.rm=T),
                      USD=sum(USD,na.rm=T),
                      perCapita=sum(perCapita,na.rm=T),
                      perStore=sum(perStore,na.rm=T),
                      latitude=mean(latitude),
                      longitude=mean(longitude)) %>% 
            filter(!is.na(County))

# Filter to only include 1 kind
my_summary = cannabis.summary %>% filter(kind==my_kind)

# Sum sales from Reported and NR
my_summary_plot <- my_summary %>% group_by(County) %>% 
            summarise(n.stores=mean(n.stores),
                      latitude=mean(latitude),
                      longitude=mean(longitude),
                      USD.total=sum(USD),
                      perCapita.total=sum(perCapita),
                      perStore.total=sum(perStore))

# Get only the Reported 
my_summary_reported <- filter(my_summary,!is.Estimate) %>% 
            select(County,USD:perStore) %>% 
            rename(USD.reported=USD,
                   perCapita.reported=perCapita,
                   perStore.reported=perStore)

# Join Summed Reproted + NR and only Reported
my_summary_plot <- full_join(my_summary_plot,my_summary_reported)
            
            


my_summary_plot
```



```{r }
# user option
radiusscale = 1


no_cannabis <- my_summary_plot %>% filter(USD.total==0)
with_cannabis <- my_summary_plot %>% filter(USD.total>0)
with_reports <- my_summary_plot %>% filter(USD.reported>0)
only_estimates <- my_summary_plot %>% filter(USD.reported==0 & USD.total>0)

#
mycannabissalesmap <- my_summary_plot %>% 
            leaflet() %>% addProviderTiles(providers$CartoDB) %>% 
            setView(lat=40,lng=-105,zoom=6)

if (estimate_option) {
            
            
            mycannabissalesmap <- mycannabissalesmap %>%
                        addCircles(lat=with_cannabis$latitude, 
                       lng=with_cannabis$longitude,
                       radius = sqrt(with_cannabis$USD.total*radiusscale),
                       label=paste(with_cannabis$County,': Report $',
                                   as.character(round(with_cannabis$USD.reported/10^6,1)),
                                   ', Estimate $',
                                   as.character(round(with_cannabis$USD.total/10^6,1)),
                                   ' Million USD', sep=''),
                       color='gray',weight=1,fillOpacity = 0.3) 
} else{
            
            mycannabissalesmap <- mycannabissalesmap %>% 
                        addCircles(lat=only_estimates$latitude, 
                       lng=only_estimates$longitude,
                       radius = 1,
                       label=paste(only_estimates$County,': NR', sep=''),
                       color='red',weight=1)
}

mycannabissalesmap <- mycannabissalesmap %>% 
            addCircles(lat=with_reports$latitude, 
                       lng=with_reports$longitude,
                       radius=sqrt(with_reports$USD.reported*radiusscale),
                       label=paste(with_reports$County,': Report $',
                                   as.character(round(with_reports$USD.reported/10^6,1)),
                                   ' Million USD', sep=''),
                       color='darkgreen',weight = 1,fillOpacity = .3)

mycannabissalesmap <- mycannabissalesmap %>% 
            addCircles(lat=no_cannabis$latitude, lng=no_cannabis$longitude,
                       radius=1, weight=1, color='blue',
                       label=paste(no_cannabis$County, '-'))



mycannabissalesmap
```